### ISSUE TITLE
Site becomes disoriented in a mobile viewport

### ISSUE THREAD

**Issue by gaurav-saiteja** [21R01A7263/QR_gen-project#1]
Here's what happens to the interface when operated on a mobile viewport.

![image](https://github.com/21R01A7263/QR_gen-project/assets/128503039/220a83c4-e805-4917-8f2a-1fa6e16a2324)

And the generated QR image is not visible too.

**Comment by Agnik7** [comment]
Hi, I am taking part in Hacktoberfest and would love to work on this issue. Requesting the maintainer(s) to kindly assign this issue to me.

**Comment by saffi-786** [comment]
Hey @21R01A7263 , I think there's some need for responsiveness to be added to the project.
I would like to work on this issue. Please assign the issue to me.

**Comment by gaurav-saiteja** [comment]
> Hi, I am taking part in Hacktoberfest and would love to work on this issue. Requesting the maintainer(s) to kindly assign this issue to me.

Hey @Agnik7. You are assigned to this issue. Good Luck!

**Comment by gaurav-saiteja** [comment]
> Hey @21R01A7263 , I think there's some need for responsiveness to be added to the project. I would like to work on this issue. Please assign the issue to me.

Sure, @saffi-786. This issue has also been assigned to you. Make sure to submit your pull request anytime during "Hacktober" Fest.

**Comment by Agnik7** [comment]
@21R01A7263 I have raised a PR #2 . Kindly review it. Have a nice day!!!

**Comment by saffi-786** [comment]
@21R01A7263 I have raised PR #3. Please review it.

**Comment by Agnik7** [comment]
@21R01A7263 I have a request. If possible, kindly add the topic of Hacktoberfest in your repository as well, otherwise these PRs will not be counted for hacktoberfest. I apologise for the inconvinience caused. Thank you!!

**Comment by gaurav-saiteja** [comment]
> @21R01A7263 I have a request. If possible, kindly add the topic of Hacktoberfest in your repository as well, otherwise these PRs will not be counted for hacktoberfest. I apologise for the inconvinience caused. Thank you!!

Thanks for the info @Agnik7. I have now reviewed your pull request and added the topic "hacktoberfest" to this repository.
